// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include "../inst/include/odeintr.h"
#include <Rcpp.h>

using namespace Rcpp;

// integrate_sys_
List integrate_sys_(Function derivs, Function recfun, state_type init, double duration, double step_size, double start);
RcppExport SEXP odeintr_integrate_sys_(SEXP derivsSEXP, SEXP recfunSEXP, SEXP initSEXP, SEXP durationSEXP, SEXP step_sizeSEXP, SEXP startSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< Function >::type derivs(derivsSEXP);
    Rcpp::traits::input_parameter< Function >::type recfun(recfunSEXP);
    Rcpp::traits::input_parameter< state_type >::type init(initSEXP);
    Rcpp::traits::input_parameter< double >::type duration(durationSEXP);
    Rcpp::traits::input_parameter< double >::type step_size(step_sizeSEXP);
    Rcpp::traits::input_parameter< double >::type start(startSEXP);
    __result = Rcpp::wrap(integrate_sys_(derivs, recfun, init, duration, step_size, start));
    return __result;
END_RCPP
}
