// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// integrate
SEXP integrate(Function derivs, Function obs, Function comb, NumericVector init, double from, double to, double by);
RcppExport SEXP odeintr_integrate(SEXP derivsSEXP, SEXP obsSEXP, SEXP combSEXP, SEXP initSEXP, SEXP fromSEXP, SEXP toSEXP, SEXP bySEXP) {
BEGIN_RCPP
    SEXP __sexp_result;
    {
        Rcpp::RNGScope __rngScope;
        Rcpp::traits::input_parameter< Function >::type derivs(derivsSEXP );
        Rcpp::traits::input_parameter< Function >::type obs(obsSEXP );
        Rcpp::traits::input_parameter< Function >::type comb(combSEXP );
        Rcpp::traits::input_parameter< NumericVector >::type init(initSEXP );
        Rcpp::traits::input_parameter< double >::type from(fromSEXP );
        Rcpp::traits::input_parameter< double >::type to(toSEXP );
        Rcpp::traits::input_parameter< double >::type by(bySEXP );
        SEXP __result = integrate(derivs, obs, comb, init, from, to, by);
        PROTECT(__sexp_result = Rcpp::wrap(__result));
    }
    UNPROTECT(1);
    return __sexp_result;
END_RCPP
}
