// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include "../inst/include/odeintr.h"
#include <Rcpp.h>

using namespace Rcpp;

// integrate_sys_const
List integrate_sys_const(Function derivs, Function recfun, state_type init, double duration, double step_size, double start, double atol, double rtol);
RcppExport SEXP odeintr_integrate_sys_const(SEXP derivsSEXP, SEXP recfunSEXP, SEXP initSEXP, SEXP durationSEXP, SEXP step_sizeSEXP, SEXP startSEXP, SEXP atolSEXP, SEXP rtolSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< Function >::type derivs(derivsSEXP);
    Rcpp::traits::input_parameter< Function >::type recfun(recfunSEXP);
    Rcpp::traits::input_parameter< state_type >::type init(initSEXP);
    Rcpp::traits::input_parameter< double >::type duration(durationSEXP);
    Rcpp::traits::input_parameter< double >::type step_size(step_sizeSEXP);
    Rcpp::traits::input_parameter< double >::type start(startSEXP);
    Rcpp::traits::input_parameter< double >::type atol(atolSEXP);
    Rcpp::traits::input_parameter< double >::type rtol(rtolSEXP);
    __result = Rcpp::wrap(integrate_sys_const(derivs, recfun, init, duration, step_size, start, atol, rtol));
    return __result;
END_RCPP
}
// integrate_sys_adapt
List integrate_sys_adapt(Function derivs, Function recfun, state_type init, double duration, double step_size, double start, double atol, double rtol);
RcppExport SEXP odeintr_integrate_sys_adapt(SEXP derivsSEXP, SEXP recfunSEXP, SEXP initSEXP, SEXP durationSEXP, SEXP step_sizeSEXP, SEXP startSEXP, SEXP atolSEXP, SEXP rtolSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< Function >::type derivs(derivsSEXP);
    Rcpp::traits::input_parameter< Function >::type recfun(recfunSEXP);
    Rcpp::traits::input_parameter< state_type >::type init(initSEXP);
    Rcpp::traits::input_parameter< double >::type duration(durationSEXP);
    Rcpp::traits::input_parameter< double >::type step_size(step_sizeSEXP);
    Rcpp::traits::input_parameter< double >::type start(startSEXP);
    Rcpp::traits::input_parameter< double >::type atol(atolSEXP);
    Rcpp::traits::input_parameter< double >::type rtol(rtolSEXP);
    __result = Rcpp::wrap(integrate_sys_adapt(derivs, recfun, init, duration, step_size, start, atol, rtol));
    return __result;
END_RCPP
}
